[package]
name = "async-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.21" }
tokio = {version = "1.18.0", features = ["full"] }
